name: Rust

on: [push]

jobs:
  ci:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-latest, windows-2022]

    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: cargo fmt -- --check --verbose
    - name: Lint
      run: cargo check --verbose
    - name: Build dev
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
